version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_for_equilibria
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $DATABASE_USER
      MYSQL_PASSWORD: $DATABASE_PASSWORD
      MYSQL_ROOT_HOST: '%'
    command: --default-authentication-plugin=mysql_native_password --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./build/init.sql:/docker-entrypoint-initdb.d/init.sql:ro  # Use 'ro' (read-only) for init.sql

volumes:
  mysql_data:
